duckdb:
  outputs:
    dev:
      type: duckdb
      path: ./jaffle_shop.duckdb
      database: jaffle_shop
      schema: DAVIDE_JAFFLE_SHOP
      threads: 4
  target: dev

snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_SANDBOX_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_SANDBOX_USER') }}"
      authenticator: externalbrowser
      database: DAVIDE_DBT
      warehouse: TRANSFORMING
      schema: DAVIDE_JAFFLE_SHOP
      threads: 8
